### ISSUE TITLE
Dev Tools: Events

### ISSUE THREAD

**Issue by vajonam** [seangreen2/slate_theme#11]
Thiis is also black on black. Should be primary-color 

![image](https://user-images.githubusercontent.com/152501/73413635-45d34980-42da-11ea-8f5b-b0f5a1e4bb82.png)

Not quite sure where to start here but thought I'd report it to be fixed.

**Comment by TomBrien** [comment]
In this screenshot the button is disabled as nothing has been entered into the text box.
