### ISSUE TITLE
New supervisor plugin update line

### ISSUE THREAD

**Issue by tamet83** [seangreen2/slate_theme#12]
Hi,

could you please change the update alert line colour?
Now is grey and it very difficult to notice.

Con you do something about it?
Following you'll find a screenshot.

![Image from iOS](https://user-images.githubusercontent.com/7949570/74683356-efff0c80-51c8-11ea-8eda-8cddf3b0ea2f.jpg)

Many thanks,
Matteo

**Comment by seangreen2** [comment]
Hmm, I don't use Hassio but if someone else does and can find out what attribute this is pulling from, I would be happy to make adjustments.

**Comment by marima84** [comment]
It seems is related to this attribute `accent-color:`

**Comment by xbmcnut** [comment]
Same issue with Supervisor and Core updates. Black is only just visible.
![image](https://user-images.githubusercontent.com/1492137/81363392-585dea00-9137-11ea-9f8e-9d7b784df037.png)

**Comment by xbmcnut** [comment]
Odd. Just updated to Supervisor 221 and problem fixed. Go figure.
![image](https://user-images.githubusercontent.com/1492137/81363545-b4c10980-9137-11ea-9570-c2a0d0143815.png)

**Comment by xbmcnut** [comment]
In saying that, the back arrow is still not visible.
![image](https://user-images.githubusercontent.com/1492137/81363669-0073b300-9138-11ea-8f38-e499d3b35ffe.png)

**Comment by Poeschl** [comment]
Supervisor: 224
Home Assistant 0.110.2
Frontend-Version: 20200519.4

And its looking fine.

![image](https://user-images.githubusercontent.com/5469257/82832702-2204c680-9ebc-11ea-873a-725aeed6fe92.png)
