### ISSUE TITLE
Theme issues in HA Core 2022.3.0+

### ISSUE THREAD

**Issue by MonkWho** [seangreen2/slate_theme#20]
Looks like HA Core 2022.3.0+ broke a bunch of stuff in the theme.

Dropdown selectors:
![image](https://user-images.githubusercontent.com/31880166/156905366-8f54b9ed-d4d5-4b04-9eec-5808dafd036b.png)

Search fields:
![image](https://user-images.githubusercontent.com/31880166/156905375-b5bcdca0-83ba-453b-a7ab-0d4a0d3c266a.png)

Integration sub list:
![image](https://user-images.githubusercontent.com/31880166/156905382-3cf769a2-21f9-4762-95f4-9a60e6c36c71.png)

Entity code editor:
![image](https://user-images.githubusercontent.com/31880166/156906026-5127f9e6-5594-4a1d-b979-d31e326c41d2.png)

There might be others.

**Comment by Royrdan** [comment]
Yep same for me. Guessing its the new Material Web Components (MWC)

**Comment by MonkWho** [comment]
Looks like fa8ae56097de9275c27dcb75706d735e9d01b605 fixed the issue. Thank you for your work.
