### ISSUE TITLE
divider-color - Recommended Change

### ISSUE THREAD

**Issue by tommyjlong** [seangreen2/slate_theme#21]
I use HA's Google calendar.  When using the month view, the square cells that encapsulate the events for each day are hard to visually delineate.
The calendar uses the `divider-color` to delineate these cells.  `divider-color` is currently set to `rgba(0, 0, 0, .12)` which makes the divider line black.
Here is what it looks like:
![image](https://user-images.githubusercontent.com/35182132/157489716-7a10f7fb-0c1e-4a8f-8601-6640157a4757.png)

I recommend changing `divider-color` to `rgba(225, 225, 225, .12)`.  This is also the same setting HA uses for its default dark theme.
Here is what it looks like with the change:
![image](https://user-images.githubusercontent.com/35182132/157486135-d8cf362c-f80f-4d39-8eb0-6d7ba061a607.png)

**Comment by seangreen2** [comment]
Great idea. will make the change.
