### ISSUE TITLE
Secondary color mushroom card white

### ISSUE THREAD

**Issue by JohnnyM84** [seangreen2/slate_theme#27]
With the v3.4.0 update of the mushroom card the secondary color of the cards is white.
This can be solved by adding this to the theme:
mush-card-secondary-color: ‘#b58e31’

i think more people are using mushroom cards so can this be added?

**Comment by seangreen2** [comment]
Can you verify adding that works? I added it to my yaml to test and nothing changed.

**Comment by JohnnyM84** [comment]
> Can you verify adding that works? I added it to my yaml to test and nothing changed.

Yes, I have added it and for me it works.

**Comment by JohnnyM84** [comment]
![image](https://github.com/seangreen2/slate_theme/assets/57282709/15bf2b06-7283-4179-a87f-031660ca9f38)

**Comment by seangreen2** [comment]
Ah, it's working for me now. Added and thanks for the fix.
