### ISSUE TITLE
Configuration > Devices with white background

### ISSUE THREAD

**Issue by marciogranzotto** [seangreen2/slate_theme#5]
![image](https://user-images.githubusercontent.com/11080704/65927833-b6706500-e3d1-11e9-8b36-46eb0d1f79f6.png)

The background and the texts are white, so it's kind of unusable.

**Comment by marciogranzotto** [comment]
Oops, sorry, wrong theme!

**Comment by michaellunzer** [comment]
@marciogranzotto I'm experiencing the same issue with this theme on the new "Unused entities" card that changed in HA 0.99.2/3

![image](https://user-images.githubusercontent.com/10967175/66108785-27ea1800-e578-11e9-92bc-41c6be05d7b2.png)
