### ISSUE TITLE
hass.io won't load the Theme

### ISSUE THREAD

**Issue by mygrexit** [seangreen2/slate_theme#7]
Hello Guys,

probably my fault but the Theme won't activate.

I'm using hassio (latest version) on a 3B+

Here's what i did:

1. Installed hacs
2. Enabled hacs, enabled themes during the configuration process too (clicked the checkbox)
3. Downloaded slate from the community market
4. Checked if the "themes" folder is in the config directory (it is!)
5. restarted hass.io multiple times

I deleted the cache but it just stays white. What am i missing?

**Comment by mygrexit** [comment]
Okay, i found it out myself.

I had to add:

`frontend:
themes: !include_dir_merge_named themes`

to my configuration.yaml

And then you can switch it by clicking on your user name on the bottom left.

I think it would be really useful to add that to the documentation of the slate theme. For me as a beginner it was quite hard to gather all the information from 3 different sources.

**Comment by seangreen2** [comment]
Good point, I updated the readme to be more beginner friendly.
