### ISSUE TITLE
Problematic colour for "label-badge-red"

### ISSUE THREAD

**Issue by siku2** [seangreen2/slate_theme#8]
The theme currently uses the primary colour for "label-badge-red", but the primary colour ("primary-color") is blue-ish, not red.
This is a problem because the [Gauge card](https://www.home-assistant.io/lovelace/gauge/) uses "label-badge-red" for [severity red](https://www.home-assistant.io/lovelace/gauge/#red).
Yellow and green are unaffected, only red turns into a blue tone instead.

Is there a reason for this to stay or could this be adjusted to better reflect the name?
I manually adjusted the colour to use "google-red-500" instead and I haven't encountered any graphical problems so far.

**Comment by vajonam** [comment]
This works for me as well, nice to have properly colored gauges.
