### ISSUE TITLE
Person - device chooser popup is white

### ISSUE THREAD

**Issue by vajonam** [seangreen2/slate_theme#9]
on 0.104.3, the popup when choosing a device to make up a person entity is white. this makes it very hard to see the icon type and in stick with the dark, it should be a black background. 

![image](https://user-images.githubusercontent.com/152501/73235960-9887f680-415e-11ea-91fb-68625c572c7a.png)

The whole popup needs some more styling

**Comment by vajonam** [comment]
Title: needs to be lighter text not black

Select devices that belong to this person - needs to be lighter 

popup background needs to be darker. 

I haven't worked out which items define these yet..

**Comment by seangreen2** [comment]
Unfortunately until we figure out what items those are, I can't fix it appropriately. I'll do some digging but hopefully someone will chime in with an answer.

**Comment by vajonam** [comment]
Here you go. These skin the popup correct. 

```
  material-background-color: "var(--paper-listbox-background-color)"
  material-secondary-background-color: '#515151'
  material-body-text-color: '#adadad'
```

![image](https://user-images.githubusercontent.com/152501/73408484-5a0f4a80-42ca-11ea-87ab-06f809a0800a.png)

There is still some black text on that person screen I am working on that now.

**Comment by seangreen2** [comment]
Got it! THanks for this, everything should be good to go now. Let me know if you find anything else.
